// <auto-generated />
namespace CardGames.MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AddCardInList : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddCardInList));
        
        string IMigrationMetadata.Id
        {
            get { return "201602072216346_AddCardInList"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
